const fs = require("fs");
const path = require("path");
const { optimize } = require("svgo");

const HOST = process.env.HOST || "admin.eazyiot.com";
const ORG = process.env.ORG || "";

// Constants
const ICON_REPO_OWNER = "JacobMire";
const ICON_REPO_NAME = "icon-library";
const ICON_CDN_BASE_URL = `https://cdn.jsdelivr.net/gh/${ICON_REPO_OWNER}/${ICON_REPO_NAME}`;

// 1. Point dynamically to the correct isolated sub-folder
const isTenant = HOST !== "admin.eazyiot.com" && ORG;
const TARGET_FOLDER = isTenant ? `tenant_svgs/${HOST}${ORG}` : "svg";
const SVG_DIR = path.join(__dirname, "../", TARGET_FOLDER);

// Output file logic:
let cssFileName = "icons.css";
if (isTenant) {
  cssFileName = `${HOST}${ORG}icons.css`;
}
const OUTPUT_FILE = path.join(__dirname, "../", cssFileName);

// Create folder locally to prevent crash if empty
if (!fs.existsSync(SVG_DIR)) {
  fs.mkdirSync(SVG_DIR, { recursive: true });
}

// 2. Configure JSdelivr with TARGET_FOLDER
const TAG = process.env.TAG || "latest";
const CDN_BASE = `${ICON_CDN_BASE_URL}@${TAG}/${TARGET_FOLDER}`;

function validateSVG(content, file) {
  if (!content.includes("<svg")) throw new Error(`${file} is not a valid SVG`);
  if (!content.includes("viewBox")) throw new Error(`${file} missing viewBox`);
}

function processSVGs() {
  const files = fs.readdirSync(SVG_DIR);

  files.forEach((file) => {
    if (!file.endsWith(".svg")) return;

    let filePath = path.join(SVG_DIR, file);

    const normalized = "ez-" + file.replace(/^ez-+/, "");
    const newPath = path.join(SVG_DIR, normalized);

    if (file !== normalized) {
      fs.renameSync(filePath, newPath);
      filePath = newPath;
      console.log(`Renamed: ${file} → ${normalized}`);
    }

    const svg = fs.readFileSync(filePath, "utf-8");
    validateSVG(svg, normalized);

    const result = optimize(svg, {
      multipass: true,
      plugins: ["removeDimensions", "removeComments", "removeMetadata"],
    });

    fs.writeFileSync(filePath, result.data);
  });
}

function generateCSS() {
  const files = fs
    .readdirSync(SVG_DIR)
    .filter((f) => f.endsWith(".svg"))
    .sort();

  let css = `/* Generated by build-icons — do not edit manually */\n/* SVG tag: ${TAG} */\n\n.ez-icon {\n  display: inline-block;\n  width: 1em;\n  height: 1em;\n  background-color: currentColor;\n  -webkit-mask-size: contain;\n  mask-size: contain;\n  -webkit-mask-repeat: no-repeat;\n  mask-repeat: no-repeat;\n}\n`;

  files.forEach((file) => {
    const className = file.replace(".svg", "").replace(/^ez-/, "");
    css += `\n.ez-icon-${className} {\n  -webkit-mask-image: url("${CDN_BASE}/${file}");\n  mask-image: url("${CDN_BASE}/${file}");\n}\n`;
  });

  return css;
}

function run() {
  processSVGs();
  const css = generateCSS();
  fs.writeFileSync(OUTPUT_FILE, css);
  console.log(`✅ Build complete → ${cssFileName} (SVG tag: ${TAG})`);
}

run();
