const fs = require("fs");
const path = require("path");
const { optimize } = require("svgo");

// Constants
const ICON_REPO_OWNER = "miteshb-eazyiot";
const ICON_REPO_NAME = "eazyicons";
const ICON_CDN_BASE_URL = `https://cdn.jsdelivr.net/gh/${ICON_REPO_OWNER}/${ICON_REPO_NAME}`;
const TAG = process.env.TAG || "latest";

function validateSVG(content, file) {
  if (!content.includes("<svg")) throw new Error(`${file} is not a valid SVG`);
  if (!content.includes("viewBox")) throw new Error(`${file} missing viewBox`);
}

function processDirectory(targetFolder, cssFileName) {
  const svgDir = path.join(__dirname, "../", targetFolder);
  const outputFile = path.join(__dirname, "../", cssFileName);

  if (!fs.existsSync(svgDir)) {
    console.log(`Skipping: ${targetFolder} (not found)`);
    return;
  }

  const cdnBase = `${ICON_CDN_BASE_URL}@${TAG}/${targetFolder}`;
  const files = fs.readdirSync(svgDir).filter((f) => f.endsWith(".svg"));

  // 1. Process & Optimize SVGs
  files.forEach((file) => {
    let filePath = path.join(svgDir, file);
    const normalized = "ez-" + file.replace(/^ez-+/, "");
    const newPath = path.join(svgDir, normalized);

    if (file !== normalized) {
      if (fs.existsSync(newPath)) {
        fs.unlinkSync(filePath);
      } else {
        fs.renameSync(filePath, newPath);
      }
      filePath = newPath;
      console.log(`Renamed: ${file} → ${normalized} in ${targetFolder}`);
    }

    const svg = fs.readFileSync(filePath, "utf-8");
    try {
      validateSVG(svg, normalized);
      const result = optimize(svg, {
        multipass: true,
        plugins: ["removeDimensions", "removeComments", "removeMetadata"],
      });
      fs.writeFileSync(filePath, result.data);
    } catch (err) {
      console.error(
        `Error processing ${normalized} in ${targetFolder}:`,
        err.message,
      );
    }
  });

  // 2. Generate CSS
  const updatedFiles = fs
    .readdirSync(svgDir)
    .filter((f) => f.endsWith(".svg"))
    .sort();

  let css = `/* Generated by build-icons — do not edit manually */\n/* SVG tag: ${TAG} */\n\n.ez-icon {\n  display: inline-block;\n  width: 1em;\n  height: 1em;\n  background-color: currentColor;\n  -webkit-mask-size: contain;\n  mask-size: contain;\n  -webkit-mask-repeat: no-repeat;\n  mask-repeat: no-repeat;\n}\n`;

  updatedFiles.forEach((file) => {
    const className = file.replace(".svg", "").replace(/^ez-/, "");
    css += `\n.ez-icon-${className} {\n  -webkit-mask-image: url("${cdnBase}/${file}");\n  mask-image: url("${cdnBase}/${file}");\n}\n`;
  });

  fs.writeFileSync(outputFile, css);
  console.log(`✅ Build complete → ${cssFileName} (Folder: ${targetFolder})`);
}

function run() {
  console.log(`🚀 Starting Icon Sync (Tag: ${TAG})`);

  // 1. Process Global Icons
  processDirectory("svg", "icons.css");

  // 2. Process Tenant Icons
  const tenantBase = path.join(__dirname, "../tenant_svgs");
  if (fs.existsSync(tenantBase)) {
    const tenants = fs
      .readdirSync(tenantBase, { withFileTypes: true })
      .filter((dirent) => dirent.isDirectory())
      .map((dirent) => dirent.name);

    tenants.forEach((tenant) => {
      processDirectory(`tenant_svgs/${tenant}`, `${tenant}icons.css`);
    });
  }

  console.log("🏁 All icon sets synchronized.");
}

run();
